#!/usr/bin/env bash

echo tutorial files
pushd .. > /dev/null
tchart skills.txt skills.tikz
pdftex -interaction=batchmode skills.tex > /dev/null
pdfcrop --margins "30 10 30 10" skills.pdf cropped.pdf > /dev/null
convert -density 400 cropped.pdf -quality 80 skills.jpg > /dev/null
rm skills.tikz *.pdf *.pgf *.log > /dev/null
popd > /dev/null

