#!/usr/bin/env bash

shopt -s nullglob
for fn in *.txt
do
	echo $fn
	tchart $fn drawing.tikz
	pdftex -interaction=batchmode drawing-template.tex > /dev/null
	pdfcrop --margins "30 5 60 10" drawing-template.pdf cropped.pdf > /dev/null
	convert -density 300 cropped.pdf -quality 80 ../${fn%.*}.jpg > /dev/null
	rm drawing.tikz drawing-template.pdf cropped.pdf drawing-template.log drawing-template.pgf > /dev/null
done

echo tutorial files
pushd .. > /dev/null
tchart skills.txt skills.tikz
pdftex -interaction=batchmode skills.tex > /dev/null
pdfcrop --margins "30 10 30 10" skills.pdf cropped.pdf > /dev/null
convert -density 300 cropped.pdf -quality 80 skills.jpg > /dev/null
rm skills.tikz *.pdf *.pgf *.log > /dev/null
popd > /dev/null

echo README.template
ruby -pe '$_.sub!( /([^@]*)@include (.*)\n/ ) { |m| `sed '"'"'s/^/#{$1}/'"'"' < #{$2}` }' < README.template > ../../../README.md
